EXP_DIR: dense_cap
DEBUG_ALL: False
LIMIT_RAM: True
TRAIN:
  HAS_RPN: True
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  SUMMARY_INTERVAL: 10
  RPN_BATCHSIZE: 256
  BATCH_SIZE: 256
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
  FG_FRACTION: 0.5
  RPN_NMS_THRESH: 0.7
  MAX_SIZE: 720
RESNET:
  FIXED_BLOCKS: 3
TEST:
  HAS_RPN: True
  RPN_NMS_THRESH: 0.6
  NMS: 0.5
  RPN_POST_NMS_TOP_N: 300
  MAX_SIZE: 720
