EXP_DIR: Densecap_res50_context_all
DEBUG_ALL: False
ALL_TEST: False
ALL_TEST_NUM_TRAIN: 100
ALL_TEST_NUM_VAL: 100
ALL_TEST_NUM_TEST: 1000
LIMIT_RAM: False
EMBED_DIM: 512
CONTEXT_FUSION: True
TRAIN:
  HAS_RPN: True
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  SUMMARY_INTERVAL: 10
  RPN_BATCHSIZE: 256
  BATCH_SIZE: 256
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
  FG_FRACTION: 0.5
  RPN_NMS_THRESH: 0.7
  MAX_SIZE: 720
  USE_FLIPPED: True
  LR_DIY_DECAY: True
  STEPSIZE: [100000]
  WEIGHT_INITIALIZER: normal
  # EXP_DECAY_RATE: 0.5
  # EXP_DECAY_STEPS: 500
RESNET:
  FIXED_BLOCKS: 3
TEST:
  HAS_RPN: True
  RPN_NMS_THRESH: 0.6
  NMS: 0.5
  RPN_POST_NMS_TOP_N: 300
  MAX_SIZE: 720
